
/*****************IMPORTS GENERATED BY MASSA-PROTO-CLI*****************/

import {
  OperationOutputs,
} from "./Ru1v2WbjYYCaller";
import { getEvents } from "./commonHelper";
import { IBaseAccount } from "@massalabs/massa-web3/dist/esm/interfaces/IBaseAccount";
import {
  IEvent,
  ICallData,
} from "@massalabs/massa-web3";


/*****************GENERATED BY PROTOC*****************/

// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "sum.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sumHelper
 */
export interface sumHelper {
    /**
     * @generated from protobuf field: uint64 a = 1;
     */
    a: bigint;
    /**
     * @generated from protobuf field: uint64 b = 2;
     */
    b: bigint;
}
/**
 * @generated from protobuf message sumRHelper
 */
export interface sumRHelper {
    /**
     * @generated from protobuf field: uint64 value = 1;
     */
    value: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class sumHelper$Type extends MessageType<sumHelper> {
    constructor() {
        super("sumHelper", [
            { no: 1, name: "a", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "b", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<sumHelper>): sumHelper {
        const message = { a: 0n, b: 0n };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<sumHelper>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: sumHelper): sumHelper {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 a */ 1:
                    message.a = reader.uint64().toBigInt();
                    break;
                case /* uint64 b */ 2:
                    message.b = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: sumHelper, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 a = 1; */
        if (message.a !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.a);
        /* uint64 b = 2; */
        if (message.b !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.b);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sumHelper
 */
export const sumHelper = new sumHelper$Type();
// @generated message type with reflection information, may provide speed optimized methods
class sumRHelper$Type extends MessageType<sumRHelper> {
    constructor() {
        super("sumRHelper", [
            { no: 1, name: "value", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<sumRHelper>): sumRHelper {
        const message = { value: 0n };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<sumRHelper>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: sumRHelper): sumRHelper {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 value */ 1:
                    message.value = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: sumRHelper, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 value = 1; */
        if (message.value !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sumRHelper
 */
export const sumRHelper = new sumRHelper$Type();



/*****************GENERATED BY MASSA-PROTO-CLI*****************/

const OUTPUTS_PREFIX = 'Resultsum:';

export async function sumExtractOutputsAndEvents(
  contractAddress: string,
  functionName: string,
  args: Uint8Array,
  coins: bigint,
  returnType: string,
  account: IBaseAccount,
  nodeUrl: string,
  fee = 0n,
  maxGas = BigInt(4_294_967_295), // = max block gas limit
): Promise<OperationOutputs> {

  let events: IEvent[] = [];

  // try to call the Smart Contract
  try{
    events = await getEvents(
      { operationId:
        await account.callSmartContract(
          {
            fee: fee,
            maxGas: maxGas,
            coins: coins,
            targetAddress: contractAddress,
            functionName: functionName,
            parameter: Array.from(args),
          } as ICallData,
        ),
      },
      nodeUrl,
    )
  }
  catch (err) {
    return {
      events: events,
    } as OperationOutputs;
  }

  // if the call is successful, retrieve the outputs from the events
  let rawOutput: string | null = null;
  for (let event of events) {
    if (event.data.slice(0, OUTPUTS_PREFIX.length) == OUTPUTS_PREFIX) {
      rawOutput = event.data.slice(OUTPUTS_PREFIX.length);
      // remove the event from the list
      events.splice(events.indexOf(event), 1);
      break;
    }
  }

  // check the output and return the result
  if (rawOutput === null && returnType !== 'void') {
    const detectedEventsData = events.map((e) => e.data);
    throw new Error(
      'Output expected but not found. Events detected:\n' + '[ ' + detectedEventsData.join(' ]\n[ ') + ' ]',
    );
  }
  if(rawOutput === null && returnType === 'void') {
    return{
      events: events,
    };
  }
  if(rawOutput !== null && returnType !== 'void') {
    let output: Uint8Array = new Uint8Array(Buffer.from(rawOutput, 'base64'));
    // try to deserialize the outputs
    let deserializedOutput: bigint;
    try{
      deserializedOutput = sumRHelper.fromBinary(output).value;
  }
    catch (err) {
      throw new Error(
        'Deserialization Error: ' + err + 'Raw Output: ' + rawOutput,
      );
    }
    
    return {
      outputs: deserializedOutput,
      events: events,
    } as OperationOutputs;
  }
  throw new Error('sumCaller: Unexpected error');
}


