import { sumHelper } from "./sumHelper";

export interface TransactionDetails {
  operationId: string;
}

/** The following global variable and the next class should be in a dedicated file. */
let callSC: (address: string, funcName: string, binArguments: Uint8Array, maxCoin: bigint) => Promise<TransactionDetails>;

/**
 * A class to call the blockchain.
 */
export class BlockchainCaller {
  /**
   * Constructor for the BlockchainCaller class.
   *
   * @param {Function} caller - The function to call the blockchain.
   */
  constructor(
    caller: (
      address: string,
      funcName: string,
      binArguments: Uint8Array,
      maxCoin: bigint
    ) => Promise<TransactionDetails>
  ) {
    if (!caller) {
      throw new Error('A caller function must be provided');
    }
    callSC = caller;
  }
}

/**
 * This method have been generated by the Massa Proto CLI.
 * It allows you to call the "sum" function of the 
 * "AS121MVEYsPmEKfqsJSmgv44r3gjJEQDTK3p13Ea5mi7iGjgHBhE1" Smart Contract.
 * 
 * @remarks
 * To work properly, you need to run 'npm install @protobuf-ts/plugin' in your project folder.
 * Otherwise, this caller will not work.
 * 
 * @param {bigint} a - 
 * @param {bigint} b - 
 *
 * @returns {int64} The result of the "sum" function.
 */
 export async function sum(a: bigint, b: bigint, coins: bigint): Promise<TransactionDetails> {
  

  // Serialize the arguments
  const serializedArgs = sumHelper.toBinary({
    a: a,
    b: b
  });

  // Send the operation to the blockchain and retrieve its outputs
  return await callSC(
    'AS121MVEYsPmEKfqsJSmgv44r3gjJEQDTK3p13Ea5mi7iGjgHBhE1',
    'sum',
    serializedArgs,
    coins,
  );
}
