export const MASSA_EXEMPLE = {
    TITLE: "Hello World",
    DESCRIPTION:
        "This is a simple example of a Massa application that can display an Event generated by the smart contract.",
    TAB: "Massa - Hello World example",
};

export const CONTRACT_ADDRESS = "";
