
import { changeAgeExtractOutputsAndEvents, changeAgeHelper } from "./changeAgeHelper";
import { getAgeExtractOutputsAndEvents, getAgeHelper } from "./getAgeHelper";
import {
  IEvent,
  WalletClient,
} from "@massalabs/massa-web3";
import { IBaseAccount } from "@massalabs/massa-web3/dist/esm/interfaces/IBaseAccount";


/**
 * This interface is used to represents the outputs of the SC call.
 *
 * @see outputs - The outputs of the SC call (optional)
 * @see events - The events emitted by the SC call (optional)
 */
export interface OperationOutputs {
  outputs?: any;
  events: IEvent[];
  error?: any;
}


export class FiEXMTvDMBlockchainCaller {
  private nodeRPC: string;

  public account: IBaseAccount;
  public coins: bigint;
  public fee: bigint = 0n;
  public maxGas: bigint = BigInt(4_294_967_295); // = max block gas limit


  constructor(account: IBaseAccount, coins: bigint, nodeRPC: string, fee?: bigint, maxGas?: bigint) {
    this.nodeRPC = nodeRPC;
    this.account = account;
    this.coins = coins;
    if(fee) this.fee = fee;
    if(maxGas) this.maxGas = maxGas;
  }

  /**
   * This method have been generated by the Massa Proto CLI.
   * It allows you to instantiate a new 8FiEXMTvDMBlockchainCaller object with the default values.
   *
   * @param {WalletClient} walletClient - The wallet client object to create the account from
   * 
   * @returns {Promise<8FiEXMTvDMBlockchainCaller>} A promise that resolves to a new 8FiEXMTvDMBlockchainCaller object
   */
  static async newDefault(walletClient: WalletClient): Promise<FiEXMTvDMBlockchainCaller> {
    const nodeRPC = await walletClient.clientConfig.providers[0].url; 
    const account = await walletClient.getBaseAccount();
    if(!account) throw new Error("No account found in the wallet");
    const coins = 0n;
    return new FiEXMTvDMBlockchainCaller(account, coins, nodeRPC);
  }


  /**
   * This method have been generated by the Massa Proto CLI.
   * It allows you to call the "changeAge" function of the
   * "AS16TsiQutRP2QZNkfMupdPjFVyoabxbiEMyxXzC8V8FiEXMTvDM" Smart Contract.
   *
   * @remarks
   * To work properly, you need to run 'npm install @protobuf-ts/plugin' in your project folder.
   * Otherwise, this caller will not work.
   *
   * @param {string} name - 
   * @param {number} age - 
   *
   * @param {bigint} coins - The amount of Massa coins to send to the block creator
   *
   * @returns {Promise<OperationOutputs>} A promise that resolves to an object which contains the outputs and events from the call to changeAge.
   */
  async changeAge(
    name: string,
    age: number,
    coins?: bigint,
    fee?: bigint, 
    maxGas?:bigint
  ): Promise<OperationOutputs> {
    // Verify that the given arguments are valid
		if (age < 0) throw new Error("Invalid argument: age cannot be negative according to protobuf file.");


// Serialize the arguments
    const serializedArgs = changeAgeHelper.toBinary({
      name: name,
      age: age,
    });

    // Send the operation to the blockchain and retrieve its outputs
    if(!coins) coins = this.coins;
    if(!fee) fee = this.fee;
    if(!maxGas) maxGas = this.maxGas;

    return (
      await changeAgeExtractOutputsAndEvents(
        'AS16TsiQutRP2QZNkfMupdPjFVyoabxbiEMyxXzC8V8FiEXMTvDM',
        'changeAge',
        serializedArgs,
        coins,
        'void',
        this.account,
        this.nodeRPC,
        fee,
        maxGas,
      )
    );
  }



  /**
   * This method have been generated by the Massa Proto CLI.
   * It allows you to call the "getAge" function of the
   * "AS16TsiQutRP2QZNkfMupdPjFVyoabxbiEMyxXzC8V8FiEXMTvDM" Smart Contract.
   *
   * @remarks
   * To work properly, you need to run 'npm install @protobuf-ts/plugin' in your project folder.
   * Otherwise, this caller will not work.
   *
   * @param {string} name - 
   *
   * @param {bigint} coins - The amount of Massa coins to send to the block creator
   *
   * @returns {Promise<OperationOutputs>} A promise that resolves to an object which contains the outputs and events from the call to getAge.
   */
  async getAge(
    name: string,
    coins?: bigint,
    fee?: bigint, 
    maxGas?:bigint
  ): Promise<OperationOutputs> {
    // Serialize the arguments
    const serializedArgs = getAgeHelper.toBinary({
      name: name,
    });

    // Send the operation to the blockchain and retrieve its outputs
    if(!coins) coins = this.coins;
    if(!fee) fee = this.fee;
    if(!maxGas) maxGas = this.maxGas;

    return (
      await getAgeExtractOutputsAndEvents(
        'AS16TsiQutRP2QZNkfMupdPjFVyoabxbiEMyxXzC8V8FiEXMTvDM',
        'getAge',
        serializedArgs,
        coins,
        'number',
        this.account,
        this.nodeRPC,
        fee,
        maxGas,
      )
    );
  }

  /**
  * This method have been generated by the Massa Proto CLI.
  * It allows you to update the amount of Massa coins to send to the block creator when calling the Smart Contract.
  */
 editCoins(coins: bigint) {
   this.coins = coins;
 }
}
