name: Asynccalls CI

on:
  push:
    paths:
      - asynccalls/**

defaults:
  run:
    working-directory: ./asynccalls/contracts

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Code quality
        run: npm run fmt:check

      - name: Test
        run: npm run test
