name: Unit tests
on: [push]
jobs:
  unit-tests-helloworld:
    defaults:
      run:
        working-directory: helloworld

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./helloworld/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm run test
