name: Daily Deploy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  deploy-helloworld:
    defaults:
      run:
        working-directory: sum/contracts

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./sum/contracts/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
        env:
          JSON_RPC_URL_PUBLIC: ${{ secrets.JSON_RPC_URL_PUBLIC }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
